### PR TITLE
Printing pylint log when failed

### LINKED ISSUE #28: Git hook just prints FAILED/PASSED, no way to see what went wrong
As far as I can tell there's no way to see anything except the file that failed, so the committer has to manually run pylint to see the checks that failed.

### PR DESCRIPTION
**Pull request by kirankoduru**
Fixes #28

### CODE REVIEW

**Comment by sebdah** [comment]
Thanks for the PR @kirankoduru. I'll merge and release it later today.

**Comment by sebdah** [comment]
I had to revert this as I ran into a problem when releasing it. Will look it through as soon as I can.

**Comment by kirankoduru** [comment]
@sebdah can you tell me what should in order to fix it ? I can have a look too.

**Comment by sebdah** [comment]
All is well now, I have merged and released this PR. Thanks again for the contribution @kirankoduru

**Pull request merged**
