### PR TITLE
Add python3 and tox support

### PR DESCRIPTION
**Pull request by jAlpedrinha**
- Added support for python3
 - Added test for multiple python versions

### CODE REVIEW

**Comment by jAlpedrinha** [comment]
@sebdah Could you review this please?

**Comment by sebdah** [comment]
@jAlpedrinha: Thanks for the PR. Could you please update the code so that is runs on both Python 2.7 and 3.x?

I'm fine with moving to `tox`, but as a general feedback (no need to change for this one) is to have one PR per change, to make it easier to merge parts of code and review in isolation.

**Comment by jAlpedrinha** [comment]
Thanks @sebdah, I totally respect that, and I'm sorry to mix things. I've added tox because breaking 2.7 support is not an option, and I believe the only way to avoid regression when compatibility with both versions matter is to enforce testing.

It should be working in python 2.7, at least is passing the tests. What's broken ?

**Comment by sebdah** [comment]
@jAlpedrinha Sorry, my bad. Got distracted by https://github.com/sebdah/git-pylint-commit-hook/pull/40/files#diff-354f30a63fb0907d4ad57269548329e3L3.

I'll merge this PR now! Thanks for your contribution!

**Pull request merged**
