### PR TITLE
Stash unstaged changes before running pylint

### PR DESCRIPTION
**Pull request by evanunderscore**
Addresses issue #26. Unstaged changes are stashed using `git stash --keep-index` before running any tests, then restored using `git reset --hard` and `git stash pop --index` afterwards. Untracked files are left untouched. Note that `git stash` doesn't work if there is no initial commit, so in this case it prints a warning then behaves as it did previously.

### CODE REVIEW

**Comment by sebdah** [comment]
Thanks for this PR. I'm gonna review it.

**Comment by evanunderscore** [comment]
@sebdah Any chance you could take a look at this? I promise the diff isn't as scary as it looks; most of it is just indenting code 4 spaces to put it under the context manager. I haven't fixed the merge conflicts yet since if you decide you don't like the overall approach I'm taking there may be no point. Let me know if you'd prefer me to fix those first.

**Comment by sebdah** [comment]
@evanunderscore I'm fine with this PR, so if you get the conflicts resolved, I'll merge it.

**Comment by evanunderscore** [comment]
@sebdah Thanks, done. Build failure seems to be due to something dropping support for 3.2 (see https://github.com/travis-ci/travis-ci/issues/5517).

**Comment by hjc1710** [comment]
Just want to chime in and say that I run my own stash and pop before running `git-pylint-commit-hook` (not all my tools are nice enough to do this for me), using the same strategy outlined here. The two don't seem to conflict in the slightest and my hooks work, no extra stashes are made, no stashes are popped at the wrong time, no stashes are dropped, etc.

Didn't notice a test for this very situation, so wanted to provide some anecdotal evidence. Thanks guys! Looks like a solid implementation!

**Pull request merged**
