### PR TITLE
Use return to alternative `sys.exit` in `check_repo`

### PR DESCRIPTION
**Pull request by coldnight**
In a web project, I need check some code except Python with pre-commit
hook. If I DO NOT edit the Python files, the check will not run or exit
with 0 directly.

### CODE REVIEW

**Comment by coldnight** [comment]
Please review this PR

**Comment by coldnight** [comment]
@sebdah Hi,  could you please review this?

**Comment by sebdah** [comment]
@coldnight Sorry about that, totally missed it. I have merged and released to PyPI now.

**Comment by sebdah** [comment]
Thanks for the contribution!

**Comment by coldnight** [comment]
@sebdah Thank you!

**Pull request merged**
